In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
#creating Array

arr = np.array([[1,3,4,5,6],[2,1,3,1,4]])
print(arr)

[[1 3 4 5 6]
 [2 1 3 1 4]]


In [4]:
print(arr.ndim)

2


In [5]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
# indexing
print(arr[1]+arr[3])

6


In [8]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,1])

2


In [19]:
#slicing
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:])
print(arr[:2])
print(arr[::-1])
print(arr[1:9:2])

[3 4 5 6 7 8 9]
[1 2]
[9 8 7 6 5 4 3 2 1]
[2 4 6 8]


In [20]:
#copy vs view
x = arr.copy()
arr[0] = 10
print(x)
print(arr)

[1 2 3 4 5 6 7 8 9]
[10  2  3  4  5  6  7  8  9]


In [23]:
x = arr.view()
arr[0] = 11
print(arr)
print(x)

[11  2  3  4  5  6  7  8  9]
[11  2  3  4  5  6  7  8  9]


In [25]:
# array shape
arr.shape

(9,)

In [31]:
# iteration
for i in arr:
    print(i)

11
2
3
4
5
6
7
8
9


In [33]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([2,4,5,2,1])
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6, 2, 4, 5, 2, 1])

In [34]:
np.array_split(arr,2)

[array([1, 2, 3, 4, 5, 6]), array([2, 4, 5, 2, 1])]

In [35]:
np.where(arr==4)

(array([3, 7], dtype=int64),)

In [36]:
np.sort(arr)

array([1, 1, 2, 2, 2, 3, 4, 4, 5, 5, 6])